
### Playbook Configuration Variables
# You may modify the following variables to customize the playbook to your
# specific needs, however do not remove any variables, they are all required
# for the playbook to function.

## User info
#username: 

## aur info
paru:
  git_url: https://aur.archlinux.org/paru.git
  install_dir: /usr/bin/paru
  build_dir: /home/{{ username }}/yay
  install_shell: makepkg -sf --noconfirm
  pkg_install_shell: paru -S --noconfirm nitrogen 

yay:
  git_url: https://aur.archlinux.org/yay-bin.git
  install_dir: /usr/bin/yay
  build_dir: /home/{{ username }}/yay-bin
  install_shell: makepkg -sf --noconfirm

## zplug info
zplug:
  git_url: https://github.com/zplug/zplug
  install_dir: ~/.zplug

## Task Configuration
setup_zsh: True

## Dotfiles
## Please make sure to update 
pull_dotfiles: True

dotfiles:
    url: https://github.com/Nka700/.dotfiles.git
    version: archx220dwm
    destination: ~/.dotfiles
    packages:
      - conky
      - fcitx
      - kitty
      - local
      - picom
      - redshift
      - snownews
      - vim
      - vnc
      - xfce4
      - xorg
      - zsh

## Desktop
install_dwm: True

## dwm 
pull_suckless: True

suckless:
    url: https://github.com/Nka700/suckless.git
    version: main
    destination: /usr/local/src/suckless
    dmenu_destination: /usr/local/src/suckless/dmenu
    dwm_destination: /usr/local/src/suckless/dwm
    slstatus_destination: /usr/local/src/suckless/slstatus
    st_destination: /usr/local/src/suckless/st

## App Preferences
## ===========================
# Web Browser
# Value can be: vivaldi, firefox, brave, or chromium
browser: chromium

## When set to True, will install elinks and w3m
install_terminal_browsers: True

## Installs LibreOffice Fresh when True
install_office: True

## email client
#mailclient: aerc
#mailclient: thunderbird

## AUR vars
use_aur: True

## python packages
python:
  packages:
    - pynvim

## Installs python packages
install_pythonpkg: True

## tlp vars
configure_tlp: True
