
#due to `Ã— This environment is externally managed` error, fixed to use pacman for installing packages."
#- name: Install python pkg for user
#  become: yes
#  become_user: '{{ username }}'
#  pip:
#    name: "{{ python.packages }}"

